
const allAccordianCollapsable = document.querySelectorAll(".collapse");

// rending next button
allAccordianCollapsable.forEach((elem, idx) => {
    const div = document.createElement("div");
    div.className = "switch-form-btn";
    if (idx >= 1) {
        // Previous button
        div.innerHTML += `<button onclick="prevAccord(this)" data-current-accord=${idx} type="button" class="wo-btn wo-bg-primary text-white rounded-1">Previous</button> <!--Generated by JS--> `;
    }

    if (idx < allAccordianCollapsable.length - 1) {
        // Next button
        div.innerHTML += `<button onclick="nextAccord(this)" data-current-accord=${idx} type="button" class="wo-btn wo-bg-primary text-white rounded-1">Next</button> <!--Generated by JS--> `;
    }

    elem.appendChild(div);

})

function nextAccord(thisBtn) {
    const currentAccordIdx = thisBtn.dataset.currentAccord;
    allAccordianCollapsable[currentAccordIdx].classList.remove("show");
    allAccordianCollapsable[Number(currentAccordIdx) + 1].classList.add("show");
};

function prevAccord(thisBtn) {
    const currentAccordIdx = thisBtn.dataset.currentAccord;
    allAccordianCollapsable[currentAccordIdx].classList.remove("show");
    allAccordianCollapsable[Number(currentAccordIdx) - 1].classList.add("show");
};
